name: Constant-Time Checker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ct-checker:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/liboqs:latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure build dependencies exist
      - name: Install build dependencies
        run: |
          apt update
          apt install -y build-essential

      # Step 3: Build your constant-time checker
      - name: Compile ct-checker
        run: |
          gcc -O2 -Wall -I/usr/local/include -o ct-checker harness.c -L/usr/local/lib -loqs -lm

      # Step 4: Run the checker
      - name: Run ct-checker
        run: ./ct-checker
