name: Constant-Time Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ctcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential liboqs-dev

    - name: Build ct-checker
      run: |
        gcc -O2 -Wall -I/usr/local/include -o ct-checker harness.c -L/usr/local/lib -loqs -lm

    - name: Run ct-checker
      run: |
        ./ct-checker
