name: Constant-Time Checker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ctcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential liboqs-dev

    - name: Build ct-checker
      run: |
        gcc -O2 -Wall -I/usr/local/include -o ct-checker harness.c -L/usr/local/lib -loqs -lm
        chmod +x ct-checker

    - name: Run ct-checker
      id: run_ct
      run: |
        ./ct-checker
      continue-on-error: true

    - name: Check result
      run: |
        if grep -q "❌" <(./ct-checker); then
          echo "Timing difference detected! ❌"
          exit 1
        else
          echo "No significant timing difference ✅"
        fi
