name: Constant-Time Checker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ct-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git python3 python3-pip

      - name: Build liboqs from source
        run: |
          git clone --branch main https://github.com/open-quantum-safe/liboqs.git
          cd liboqs
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
          make -j$(nproc)
          sudo make install
          sudo ldconfig  # Ensure dynamic linker finds liboqs

      - name: Build constant-time checker
        run: |
          gcc -O2 -Wall -I/usr/local/include -o ct-checker harness.c -L/usr/local/lib -loqs -lm

      - name: Run checker
        run: ./ct-checker
